In [2]:
import numpy as np

# (i) create matrix
with open("iris.data","r") as fo:
    list = np.array([])
    for line in fo:
        number = line.split(",")
        del number[-1]
        if len(number) != 0 :
            FloatNumber = [float(s) for s in number]
            list = np.append(list,FloatNumber)

list = list.reshape(150,4)
print("(i)\n",list,"\n")

In [2]:
# (ii) count the number of specified lines
cnt = 0
for num in list:
    if num[0] > 5:
        cnt += 1

print("(ii)\n",cnt,"\n")

In [2]:
# (iii) report the average
multi = np.array([])
for num in list:
    multi = np.append(multi,num[0]*num[1])

avg = multi.mean()
print("(iii)\n",avg,"\n")

標準偏差
　平均値からどれだけばらついているかの指標
　s = √{ 1/n { Σ(n) (x_i-x_avg)^2 } }

In [2]:
# (iv) what is the std deviation
print("(iv)\n",np.std(list,axis=0)[3],"\n")

In [2]:
# (v) find specified rows
ans = np.array([])
cnt = 0
for num in list:
    if num[2]*num[3] > 1.0:
        ans = np.append(ans,num)
        cnt += 1

ans = ans.reshape(cnt,4)
print("(v)\n",ans)

np.save("small_petal",ans)

# b = np.load("small_petal.npy")
# print(b)

(i)
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3